name: Build and release

on:
  push:
    branches: [ fix/github-actions-linux ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: preinstall
      run: sudo apt-get install libxml2-utils
    - name: create_dirs
      run: mkdir -p ../my_rel ../my_build
    - name: configure_and_make
      run: ./admin/builders/ubuntu64_build.sh -s `pwd`/.. -r `pwd`/../my_rel -b `pwd`/../my_build -g
# Skip tests for now
#    - name: test
#      run: cd ../my_build/maracluster && sudo make install && make test ARGS="-V"
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: ubuntu-packages
        path: ../my_rel

  release:
    runs-on: ubuntu-latest
    needs: build-ubuntu
    # if: startsWith(github.ref, 'refs/tags/rel-')
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - run : |
        ls -R
        mkdir releases
        tar -czvf packages/ubuntu.tar.gz -C ubuntu-packages $(ls ubuntu-packages)
        rmdir *-packages
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: packages/*
        tag: ${{ github.ref }}
        overwrite: false
        file_glob: true
